services:
  api:
    image: api
    container_name: backend
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 8080:8080

  client:
    image: client
    container_name: client
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
      - 80:80
  
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432